name: on-release
on:
  workflow_dispatch:
  push:
    tags:
      - bs3*

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  MOZ_HEADLESS: 1
  CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # one run
  one_run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  # install dependencies
  install:
    runs-on: ubuntu-latest
    needs: one_run
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

  # build ngx-bootstrap
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: dist
          key: dist-${{ github.run_id }}
      - run: |
          npx nx build ngx-bootstrap --configuration=production
          npx nx prerender --configuration=production

  # update release notes in github
#  update_release_draft:
#    needs: install
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
#      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
#        with:
#          path: node_modules
#          key: node_modules-${{ hashFiles('**/package-lock.json') }}
#      - run: npm run release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # update gh_pages
  gh_pages_deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: 'gh-pages'
          path: 'gh-pages'

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: dist
          key: dist-${{ github.run_id }}

      #      - run: npm run scully
      - run: npx ts-node ./scripts/gh-pages-predeploy.ts
      - run: |
          cd gh-pages
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git config user.name $GITHUB_ACTOR
          git add -A
          git commit -am "ci: gh-pages update"
        continue-on-error: true
      - name: push to gh-pages
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6 # v0.6.0
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'
          directory: 'gh-pages'

  # publish package to another branch
  npm_publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: dist
          key: dist-${{ github.run_id }}

      # Deploy to local repo
      # see: https://github.com/marketplace/actions/push-git-subdirectory-as-branch
      - name: Deploy
        uses: s0/git-publish-subdir-action@ac113f6bfe8896e85a373534242c949a7ea74c98 # develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: dist/ngx-bootstrap
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}-release
